baseurl = "https://jakarta.ee/"
DefaultContentLanguage = "en"
title = "Jakarta EE: The New Home of Cloud Native Java"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
googleAnalytics = "UA-910670-30"
disableKinds = ["taxonomy", "taxonomyTerm"]
themesDir = "node_modules/"
enableRobotsTXT = true

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "Jakarta Enterprise Edition (EE) is the future of cloud native Java. Jakarta EE open source software drives cloud native innovation, modernizes enterprise applications and protects investments in Java EE."
  subtitle = "The New Home of Cloud Native Java"
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["Jakarta EE software", "Java EE", "cloud", "microservices", "enterprise", "open source", "innovation"]
  logo = "images/jakarta/jakarta-ee-logo.svg"
  styles = "css/styles.css"
  favicon = "images/jakarta/favicon.ico"
  share_img = "images/jakarta/jakarta_ee_400x400.png"
  gcse = "011805775785170369411:p3ec0igo0qq"
  subtheme = "jakarta"
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
  show_events = true
  call_for_action_text = "Releases"
  call_for_action_url = "/release/"
  call_for_action_icon = "fa-download"
  linkedin_url="https://www.linkedin.com/groups/13597511/"
  youtube_url="https://www.youtube.com/user/EclipseFdn"
  twitter_url="https://twitter.com/JakartaEE"
  facebook_url="https://www.facebook.com/JakartaEE"
  header_left_classes = "col-sm-4"
  main_menu_wrapper_classes = "col-sm-20 margin-top-10"
  hide_cfa_same_page = true
[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Membership"
    url = "/Membership/"
    weight = 2

[[menu.main]]
    name = "Connect"
    url = "/connect/"
    weight = 3
    
[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 4
    
[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 4
    
[[menu.main]]
    name = "Compatible Products"
    url = "/compatibility/"
    weight = 5
    
# Resource sub-menu
[[menu.main]]
    name = "Documentation"
    url = "/resources#documentation"
    parent = "Documentation"
    weight = 1

[[menu.main]]
    name = "Surveys"
    url = "/resources#surveys"
    parent = "Resources"
    weight = 2
    
[[menu.main]]
    name = "Infographics"
    url = "/resources#infographics"
    parent = "Resources"
    weight = 3
    
[[menu.main]]
    name = "Videos"
    url = "/resources#videos"
    parent = "Resources"
    weight = 4
    
[[menu.main]]
    name = "Specification Process"
    url = "/resources#specification_process"
    parent = "Resources"
    weight = 5
    
[[menu.main]]
    name = "Newsletter Archives"
    url = "/newsletter/"
    parent = "Resources"
    weight = 6
    
[[menu.main]]
    name = "Meeting Minutes"
    url = "/meeting_minutes/"
    parent = "Resources"
    weight = 7

[[menu.main]]
    name = "Blog"
    url = "https://Jakartablogs.ee"
    parent = "Resources"
    weight = 8
