[build]
publish = "website/public"
command = "./build.sh && cd website && hugo"

[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "./build.sh && cd website && hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "./build.sh && cd website && hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54.0"

[context.branch-deploy]
command = "./build.sh && cd website && hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.54.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
